language: php
sudo: required
services:
  - docker
php:
  - 5.6
install:
  - php composer.phar install
before_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
script:
  - php build.php
  - docker build .
  - git add Dockerfile
  - git commit -m "TravisCI build $TRAVIS_BUILD_NUMBER on $(date -u "+%Y-%m-%d-%H-%M-%S")"
after_success:
  - export GIT_TAG=build-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --force --tags "https://${GH_TOKEN}@${TRAVIS_REPO_SLUG}" $TRAVIS_BRANCH
